version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: strwiker_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: strwiker
      MYSQL_USER: dev_username
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
