version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: strwiker_db
    environment:
      POSTGRES_USER: dev_username
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: strwiker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/mysql

volumes:
  postgres_data:
