name: Apply db migrations
on:
  push:
    branches:
      - main

jobs:
  apply_db_migrations:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      
      - name: Apply db migrations 
        run: npx prisma migrate deploy
        env:
          POSTGRES_PRISMA_URL: ${{secrets.DATABASE_URL}}
          POSTGRES_URL_NON_POOLING: ${{secrets.DIRECT_URL}}

        