name: Push DB Schema changes
on:
  push:
    branches:
      - main

jobs:
  push_db_schema_changes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      
      - name: Push DB Schema changes with prisma
        run: npx prisma db push
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}

        